spring.application.name=facturas_sinteticas_imagenes
server.port=8081
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.base-url=https://api.openai.com/
spring.ai.openai.image.options.size=1024x1024
spring.ai.openai.image.options.quality=medium
spring.ai.retry.max-attempts=1
spring.ai.chat.client.enabled=false
event.name.image=new-image
image.model.name=gpt-image-1
logging.level.org.springframework.http.codec=DEBUG
logging.level.reactor.netty.http.client=DEBUG